apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-library-jenkins 
  description: Secure Supply Chain Example for Go Runtime http based application with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=test-library-jenkins
    jenkins.io/job-full-name: test-library-jenkins
    backstage.io/kubernetes-id: test-library-jenkins 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: jduimovich0/test-library-jenkins  
  tags: ["go", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 